// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPIyM-Z0tgR6ZJq7O-5xnB5Jz_QX1X-aw',
    appId: '1:741440698616:web:8f5d00c67291157848230d',
    messagingSenderId: '741440698616',
    projectId: 'guardian-network-89362',
    authDomain: 'guardian-network-89362.firebaseapp.com',
    storageBucket: 'guardian-network-89362.firebasestorage.app',
    measurementId: 'G-6V7S4BB428',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAEtgHSNd1fQgfYaDkxj14hJPeRNQPD8',
    appId: '1:741440698616:android:1842fc7698d7cd1248230d',
    messagingSenderId: '741440698616',
    projectId: 'guardian-network-89362',
    storageBucket: 'guardian-network-89362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCd17yHZ3A2JIUA2F-KO4-xQ_Ef9iiqh4',
    appId: '1:741440698616:ios:969b163132f820b048230d',
    messagingSenderId: '741440698616',
    projectId: 'guardian-network-89362',
    storageBucket: 'guardian-network-89362.firebasestorage.app',
    iosBundleId: 'com.guardian.network',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCd17yHZ3A2JIUA2F-KO4-xQ_Ef9iiqh4',
    appId: '1:741440698616:ios:b08bdac6beb3b22a48230d',
    messagingSenderId: '741440698616',
    projectId: 'guardian-network-89362',
    storageBucket: 'guardian-network-89362.firebasestorage.app',
    iosBundleId: 'com.example.guardianNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPIyM-Z0tgR6ZJq7O-5xnB5Jz_QX1X-aw',
    appId: '1:741440698616:web:a5133cc2cd394e1048230d',
    messagingSenderId: '741440698616',
    projectId: 'guardian-network-89362',
    authDomain: 'guardian-network-89362.firebaseapp.com',
    storageBucket: 'guardian-network-89362.firebasestorage.app',
    measurementId: 'G-JT017S1XPF',
  );
}
